server:
  port: 8888

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      #可以根据请求参数,cookie,host,请求时间,请求头等进行校验判断路由
      routes:
      - id: host_route
        uri: http://httpbin.org:80/get
        predicates:
        - Path=/lmy/** # 请求地址携带lmy的,则转发
        filters:
        - AddRequestHeader=X-Request-Foo, Bar
      # 路由到其他服务,url需要用[lb://]+[serviceId]
      - id: service-feign
        uri: lb://service-feign
        predicates:
        - Path=/to_provider/** # 如果请求地址满足/to_provider/**,则转发到 service-feign 服务
        filters:
        - StripPrefix=1 # 去除请求地址中的to_provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/